In [17]:
import pandas as pd

In [ ]:
#First pre-processing

In [42]:
reader = pd.read_csv('train_2011_2012_2013.7z/train_2011_2012_2013.csv',delimiter=";",nrows=200)

fields =['DATE','TPER_HOUR','SPLIT_COD','ACD_COD','ASS_ASSIGNMENT','CSPL_CALLS']

df=pd.DataFrame(reader,columns=fields)
print(df)

print(df.mean(0,'SPLIT_COD'))

                        DATE  TPER_HOUR  SPLIT_COD  ACD_COD  \
0    2011-04-24 01:30:00.000          1        855        1
1    2011-04-24 01:30:00.000          1       1587        1
2    2011-04-24 01:30:00.000          1       1589        1
3    2011-04-24 01:30:00.000          1       1591        1
4    2011-04-24 01:30:00.000          1       1555        1
5    2011-04-25 01:30:00.000          1         21        1
6    2011-04-25 01:30:00.000          1        711        1
7    2011-04-25 01:30:00.000          1         20        1
8    2011-04-25 01:30:00.000          1          3        1
9    2011-04-25 01:30:00.000          1        422        1
10   2011-04-25 01:30:00.000          1         10        1
11   2011-04-25 01:30:00.000          1        302        1
12   2011-04-25 01:30:00.000          1        213        1
13   2011-04-25 01:30:00.000          1        425        1
14   2011-04-25 01:30:00.000          1          2        1
15   2011-04-25 01:30:00.000          1        109        1
16   2011-04-25 01:30:00.000          1         53        1
17   2011-04-25 01:30:00.000          1        333        1
18   2011-04-25 01:30:00.000          1        423        1
19   2011-04-25 01:30:00.000          1         51        1
20   2011-04-25 01:30:00.000          1        306        1
21   2011-04-25 01:30:00.000          1         11        1
22   2011-04-25 01:30:00.000          1        420        1
23   2011-04-25 01:30:00.000          1        108        1
24   2011-04-25 01:30:00.000          1        110        1
25   2011-04-25 01:30:00.000          1          1        1
26   2011-04-25 01:30:00.000          1        319        1
27   2011-04-25 01:30:00.000          1        219        1
28   2011-04-25 01:30:00.000          1        413        1
29   2011-04-25 01:30:00.000          1          7        1
..                       ...        ...        ...      ...
170  2011-01-02 00:00:00.000          0        843        1
171  2011-01-02 00:00:00.000          0        844        1
172  2011-01-02 00:00:00.000          0        850        1
173  2011-01-02 00:00:00.000          0        701        1
174  2011-01-02 00:00:00.000          0        700        1
175  2011-01-02 00:00:00.000          0        715        1
176  2011-01-02 00:00:00.000          0          8        1
177  2011-01-02 00:00:00.000          0        419        1
178  2011-01-02 00:00:00.000          0        702        1
179  2011-01-02 00:00:00.000          0        730        1
180  2011-01-02 00:00:00.000          0        731        1
181  2011-01-02 00:00:00.000          0         12        1
182  2011-01-02 00:00:00.000          0          9        1
183  2011-01-02 00:00:00.000          0        215        1
184  2011-01-02 00:00:00.000          0        706        1
185  2011-01-02 00:00:00.000          0        717        1
186  2011-01-02 00:00:00.000          0        718        1
187  2011-01-02 00:00:00.000          0        316        1
188  2011-01-02 00:00:00.000          0        317        1
189  2011-01-02 00:00:00.000          0       1201        1
190  2011-01-02 00:00:00.000          0       1587        1
191  2011-01-02 00:00:00.000          0       1589        1
192  2011-01-03 00:00:00.000          0        711        1
193  2011-01-03 00:00:00.000          0        421        1
194  2011-01-03 00:00:00.000          0          3        1
195  2011-01-03 00:00:00.000          0        422        1
196  2011-01-03 00:00:00.000          0        302        1
197  2011-01-03 00:00:00.000          0          2        1
198  2011-01-03 00:00:00.000          0         53        1
199  2011-01-03 00:00:00.000          0        333        1

                     ASS_ASSIGNMENT  CSPL_CALLS
0                        Téléphonie           0
1                        Téléphonie           0
2                        Téléphonie           0
3                        Téléphonie           0
4                        Téléphonie           1
5                               RTC           0
6                   Gestion Renault           0
7                               RTC           0
8                              Nuit           5
9    Gestion - Accueil Telephonique           0
10              Regulation Medicale           0
11                         Services           0
12                      Tech. Total           0
13      Gestion Relation Clienteles           0
14                             Nuit           0
15                           Crises           0
16                            Japon           0
17                          Médical           1
18               Gestion Assurances           0
19                            Japon           0
20                         Domicile           0
21              Regulation Medicale           0
22                          Gestion           0
23                          Médical           0
24                          Médical           0
25                       Téléphonie           0
26                         Services           0
27                           Crises           0
28                              SAP           0
29                             Nuit           0
..                              ...         ...
170                      Téléphonie           0
171                      Téléphonie           0
172                      Téléphonie           0
173                            Nuit           0
174                         RENAULT           0
175                            Nuit           1
176                            Nuit           3
177                    Gestion Amex           0
178                            Nuit           2
179                         RENAULT           0
180                         RENAULT           0
181                            Nuit           0
182                            Nuit           3
183                     Tech. Inter           0
184                         RENAULT           0
185                         RENAULT           0
186                         RENAULT           0
187                        Domicile           0
188                        Domicile           0
189                      Téléphonie           0
190                      Téléphonie           0
191                      Téléphonie           0
192                 Gestion Renault           0
193                 Gestion Clients           0
194                            Nuit          10
195  Gestion - Accueil Telephonique           0
196                        Services           0
197                            Nuit           1
198                           Japon           0
199                         Médical           0

[200 rows x 6 columns]
TPER_HOUR       0.315
SPLIT_COD     497.335
ACD_COD         1.000
CSPL_CALLS      0.270
dtype: float64

In [19]:
print(reader)

                       DATE  DAY_OFF  DAY_DS  WEEK_END DAY_WE_DS TPER_TEAM  \
0   2011-04-24 01:30:00.000        0     NaN         1  Dimanche      Nuit
1   2011-04-24 01:30:00.000        0     NaN         1  Dimanche      Nuit
2   2011-04-24 01:30:00.000        0     NaN         1  Dimanche      Nuit
3   2011-04-24 01:30:00.000        0     NaN         1  Dimanche      Nuit
4   2011-04-24 01:30:00.000        0     NaN         1  Dimanche      Nuit
5   2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit
6   2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit
7   2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit
8   2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit
9   2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit
10  2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit
11  2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit
12  2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit
13  2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit
14  2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit
15  2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit
16  2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit
17  2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit
18  2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit
19  2011-04-25 01:30:00.000        0     NaN         0     Lundi      Nuit

    TPER_HOUR  SPLIT_COD  ACD_COD        ACD_LIB      ...       \
0           1        855        1  Entity1 G3RV6      ...
1           1       1587        1  Entity1 G3RV6      ...
2           1       1589        1  Entity1 G3RV6      ...
3           1       1591        1  Entity1 G3RV6      ...
4           1       1555        1  Entity1 G3RV6      ...
5           1         21        1  Entity1 G3RV6      ...
6           1        711        1  Entity1 G3RV6      ...
7           1         20        1  Entity1 G3RV6      ...
8           1          3        1  Entity1 G3RV6      ...
9           1        422        1  Entity1 G3RV6      ...
10          1         10        1  Entity1 G3RV6      ...
11          1        302        1  Entity1 G3RV6      ...
12          1        213        1  Entity1 G3RV6      ...
13          1        425        1  Entity1 G3RV6      ...
14          1          2        1  Entity1 G3RV6      ...
15          1        109        1  Entity1 G3RV6      ...
16          1         53        1  Entity1 G3RV6      ...
17          1        333        1  Entity1 G3RV6      ...
18          1        423        1  Entity1 G3RV6      ...
19          1         51        1  Entity1 G3RV6      ...

   CSPL_ACCEPTABLE CSPL_SERVICELEVEL CSPL_ACDAUXOUTCALLS CSPL_SLVLABNS  \
0                0                30                   0             0
1                0                15                   0             0
2                0                20                   0             0
3                0                 0                   0             0
4                1                15                   0             0
5                0                20                   0             0
6                0                30                   0             0
7                0                20                   0             0
8                5                30                   0             0
9                0                20                   0             0
10               0                20                   0             0
11               0                30                   0             0
12               0                30                   0             0
13               0                20                   0             0
14               0                30                   0             0
15               0                30                   0             0
16               0                20                   0             0
17               1                30                   0             0
18               0                20                   0             0
19               0                20                   0             0

   CSPL_SLVLOUTFLOWS CSPL_RECEIVED_CALLS CSPL_ABANDONNED_CALLS  CSPL_CALLS  \
0                  0                   0                     0           0
1                  0                   0                     0           0
2                  0                   0                     0           0
3                  0                   0                     0           0
4                  0                   1                     0           1
5                  0                   0                     0           0
6                  0                   0                     0           0
7                  0                   0                     0           0
8                  0                   5                     0           5
9                  0                   0                     0           0
10                 0                   0                     0           0
11                 0                   0                     0           0
12                 0                   0                     0           0
13                 0                   0                     0           0
14                 0                   0                     0           0
15                 0                   0                     0           0
16                 0                   0                     0           0
17                 0                   1                     0           1
18                 0                   0                     0           0
19                 0                   0                     0           0

    CSPL_ACWTIME  CSPL_ACDTIME
0              0             0
1              0             0
2              0             0
3              0             0
4              0           488
5              0             0
6              0             0
7              0             0
8           2761          1011
9              0             0
10             0             0
11             0             0
12             0             0
13             0             0
14             0             0
15             0             0
16             0             0
17          2078           271
18             0             0
19             0             0

[20 rows x 86 columns]

In [21]:
savedcols=reader.DAY_OFF

In [22]:
print(savedcols)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: DAY_OFF, dtype: int64